type PlatformType = 'normal' | 'fragile' | 'moving' | 'spring'
type StaticType = 'landed_spike'
type ItemType = 'trampoline' | 'jetpack'
type MovingType = 'witch' | 'flying_monster'
type MovingPattern = 'horizontal' | 'circular' | 'zigzag' | 'vertical' | 'repeat'
