export const CONFIG = {
    CANVAS: {
        WIDTH: 1000,
        HEIGHT: 800,
    },
    CAMERA: {
        FOLLOW_OFFSET: 200,
    },
} as const

export const KEY = {
    BACKSPACE: 'Backspace',
    TAB: 'Tab',
    ENTER: 'Enter',
    SHIFT: 'Shift',
    CTRL: 'Control',
    ALT: 'Alt',
    PAUSE: 'Pause',
    CAPS_LOCK: 'CapsLock',
    ESCAPE: 'Escape',
    SPACE: 'Space',
    PAGE_UP: 'PageUp',
    PAGE_DOWN: 'PageDown',
    END: 'End',
    HOME: 'Home',
    LEFT: 'ArrowLeft',
    UP: 'ArrowUp',
    RIGHT: 'ArrowRight',
    DOWN: 'ArrowDown',

    A: 'KeyA',
    B: 'KeyB',
    C: 'KeyC',
    D: 'KeyD',
    E: 'KeyE',
    F: 'KeyF',
    G: 'KeyG',
    H: 'KeyH',
    I: 'KeyI',
    J: 'KeyJ',
    K: 'KeyK',
    L: 'KeyL',
    M: 'KeyM',
    N: 'KeyN',
    O: 'KeyO',
    P: 'KeyP',
    Q: 'KeyQ',
    R: 'KeyR',
    S: 'KeyS',
    T: 'KeyT',
    U: 'KeyU',
    V: 'KeyV',
    W: 'KeyW',
    X: 'KeyX',
    Y: 'KeyY',
    Z: 'KeyZ',

    DIGIT_0: 'Digit0',
    DIGIT_1: 'Digit1',
    DIGIT_2: 'Digit2',
    DIGIT_3: 'Digit3',
    DIGIT_4: 'Digit4',
    DIGIT_5: 'Digit5',
    DIGIT_6: 'Digit6',
    DIGIT_7: 'Digit7',
    DIGIT_8: 'Digit8',
    DIGIT_9: 'Digit9',

    NUMPAD_0: 'Numpad0',
    NUMPAD_1: 'Numpad1',
    NUMPAD_2: 'Numpad2',
    NUMPAD_3: 'Numpad3',
    NUMPAD_4: 'Numpad4',
    NUMPAD_5: 'Numpad5',
    NUMPAD_6: 'Numpad6',
    NUMPAD_7: 'Numpad7',
    NUMPAD_8: 'Numpad8',
    NUMPAD_9: 'Numpad9',
    NUMPAD_ADD: 'NumpadAdd',
    NUMPAD_SUBTRACT: 'NumpadSubtract',
    NUMPAD_MULTIPLY: 'NumpadMultiply',
    NUMPAD_DIVIDE: 'NumpadDivide',
    NUMPAD_DECIMAL: 'NumpadDecimal',
    NUMPAD_ENTER: 'NumpadEnter',

    F1: 'F1',
    F2: 'F2',
    F3: 'F3',
    F4: 'F4',
    F5: 'F5',
    F6: 'F6',
    F7: 'F7',
    F8: 'F8',
    F9: 'F9',
    F10: 'F10',
    F11: 'F11',
    F12: 'F12',

    PRINT_SCREEN: 'PrintScreen',
    INSERT: 'Insert',
    DELETE: 'Delete',
    META: 'Meta',
    CONTEXT_MENU: 'ContextMenu',
    SCROLL_LOCK: 'ScrollLock',
} as const
