export const GAME_CONFIG = {
    PLAYER: {
        JUMP_FORCE: -800,
        MOVE_SPEED: 600,
        MAX_FALL_SPEED: 2200,
    },
    DECORATION: {
        WIDTH: 64,
        HEIGHT: 120,
    },
    PLATFORM: {
        WIDTH: 196,
        HEIGHT: 64,
        SPAWN_DISTANCE: 96,
        INITIAL_COUNT: 10,
    },
    OBSTACLES: {
        LANDED_SPIKE: {
            ICON: 'landed_spike',
            SPAWN_CHANCE: 0.1,
            WIDTH: 96,
            HEIGHT: 24,
            SPAWN_LEVEL: 1,
        },
        FLYING_MONSTER: {
            ICON: 'flying_monster',
            SPAWN_CHANCE: 0.1,
            WIDTH: 96,
            HEIGHT: 96,
            MOVE_SPEED: 400,
            SPAWN_LEVEL: 1,
        },
        WITCH: {
            ICON: 'witch',
            SPAWN_CHANCE: 0.1,
            WIDTH: 128,
            HEIGHT: 128,
            MOVE_SPEED: 200,
            MOVE_RANGE: 400,
            SPAWN_LEVEL: 3,
        },
    },
    ITEMS: {
        TRAMPOLINE: {
            ICON: 'trampoline',
            SPAWN_CHANCE: 0.5,
            WIDTH: 64,
            HEIGHT: 64,
            BOUNCE_FORCE: 1200,
        },
        JETPACK: {
            ICON: 'jetpack',
            SPAWN_CHANCE: 0.5,
            WIDTH: 64,
            HEIGHT: 64,
            FUEL: 25,
            FUEL_CONSUMPTION_RATE: 10,
        },
    },
    BACKGROUND: {
        CLOUD: {
            WIDTH: 200,
            HEIGHT: 100,
            MOVE_SPEED: 50,
            COUNT: 5,
        },
    },
    IMAGES: {
        BACKGROUND: {
            GAMEPLAY_BACKGROUND: 'gameplay_background',
            MAINMENU_BACKGROUND: 'main_menu_background',
        },
        BUTTON: {
            PLAY_BUTTON: 'play_button',
            SETTINGS_BUTTON: 'settings_button',
            BACK_BUTTON: 'back_button',
            RESTART_BUTTON: 'restart_button',
            SOUND_ON_BUTTON: 'sound_on_button',
            SOUND_OFF_BUTTON: 'sound_off_button',
        },
        CLOUD: 'cloud',
        PLATFORMS: {
            PLATFORM_1: 'platform_1',
            PLATFORM_2: 'platform_2',
            PLATFORM_3: 'platform_3',
            PLATFORM_4: 'platform_4',
            PLATFORM_5: 'platform_5',
        },
        DECORATIONS: {
            TREE_1: 'tree_1',
            TREE_2: 'tree_2',
            TREE_3: 'tree_3',
            TREE_4: 'tree_4',
            LAMP_POST_1: 'lamp_post_1',
            LAMP_POST_2: 'lamp_post_2',
        },

        BREAKABLE_PLATFORM: 'breakable_platform',
        BROKEN_PLATFORM: 'broken_platform',

        GROUND: 'ground',
        PLAYERS: {
            PLAYER_IDLE: 'player_idle',
            PLAYER_MOVE_LEFT: 'player_move_left',
            PLAYER_MOVE_RIGHT: 'player_move_right',
            PLAYER_JUMP: 'player_jump',
            PLAYER_IDLE_JETPACK: 'player_idle_jetpack',
            PLAYER_MOVE_LEFT_JETPACK: 'player_move_left_jetpack',
            PLAYER_MOVE_RIGHT_JETPACK: 'player_move_right_jetpack',
            PLAYER_DEAD: 'player_dead',
        },
    },
    AUDIO: {
        SFX: {
            TRAMPOLINE: 'trampoline',
            JUMP: 'jump',
            JETPACK: 'jetpack',
            HIT: 'hit',
            WALK: 'walk',
            BUTTON_CLICK: 'button_click',
        },
        MUSIC: {
            BACKGROUND_MUSIC: 'background_music',
        },
    },
    ANIMATIONS: {
        PLAYER_IDLE: {
            name: 'player_idle',
            frames: [
                'player_idle_1',
                'player_idle_2',
                'player_idle_3',
                'player_idle_4',
                'player_idle_5',
                'player_idle_6',
            ],
            frameRate: 500,
            loop: true,
        },
        PLAYER_IDLE_JETPACK: {
            name: 'player_idle_jetpack',
            frames: [
                'player_idle_jetpack_1',
                'player_idle_jetpack_2',
                'player_idle_jetpack_3',
                'player_idle_jetpack_4',
                'player_idle_jetpack_5',
                'player_idle_jetpack_6',
            ],
            frameRate: 500,
            loop: true,
        },
        PLAYER_MOVE_LEFT: {
            name: 'player_move_left',
            frames: [
                'player_move_left_1',
                'player_move_left_2',
                'player_move_left_3',
                'player_move_left_4',
            ],
            frameRate: 300,
            loop: true,
        },
        PLAYER_MOVE_LEFT_JETPACK: {
            name: 'player_move_left_jetpack',
            frames: [
                'player_move_left_jetpack_1',
                'player_move_left_jetpack_2',
                'player_move_left_jetpack_3',
                'player_move_left_jetpack_4',
            ],
            frameRate: 300,
            loop: true,
        },
        PLAYER_MOVE_RIGHT: {
            name: 'player_move_right',
            frames: [
                'player_move_right_1',
                'player_move_right_2',
                'player_move_right_3',
                'player_move_right_4',
            ],
            frameRate: 300,
            loop: true,
        },
        PLAYER_MOVE_RIGHT_JETPACK: {
            name: 'player_move_right_jetpack',
            frames: [
                'player_move_right_jetpack_1',
                'player_move_right_jetpack_2',
                'player_move_right_jetpack_3',
                'player_move_right_jetpack_4',
            ],
            frameRate: 300,
            loop: true,
        },
        PLAYER_JUMP: {
            name: 'player_jump',
            frames: ['player_jump_1', 'player_jump_2', 'player_jump_3'],
            frameRate: 300,
            loop: false,
        },
        PLAYER_DEAD: {
            name: 'player_dead',
            frames: ['player_dead', 'player_dead', 'player_dead'],
            frameRate: 300,
            loop: false,
        },
    },
    DIFFICULTY: 500,
    HIGH_SCORE_KEY: 'doodleJump_highScore',
    CURRENT_SCORE_KEY: 'doodleJump_currentScore',
    AUDIO_ENABLED_KEY: 'doodleJump_audioEnabled',
    MOVING_PLATFORM_SPAWN_CHANCE: 0.2,
    BREAKABLE_PLATFORM_SPAWN_CHANCE: 0.1,
}
